routes:

collections:
  /partners/:
    permalink: /partners/{slug}/
    template: page-partners
    filter: tag:[hash-mainpartnerpage,hash-partnerpage]
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
